fp=open("MyFile1.txt","r")
data=fp.read()
lc=len(data)
word_cou=len(data.split())
sc=data.count('')
nc=data.count('\n')
print(f"TOTAL\nWord={word_cou}\tSpace={sc}\tNew Line={nc}")
print("The content of file : ",data)
fp.close()